const ActionType = {
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
  SET_PLAYER: "SET_PLAYER",
  SET_FAVORITE: "SET_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
};

export default ActionType;
